name: part1

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositori
        uses: actions/checkout@v3

      - name: Configurar python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Executar proves amb unittest
        run: python -m unittest discover
